deadline:
  host_name: deadline-manager
  port: 8082
  default_group: 8cores
  default_pool: bundle
  default_limits: 

  task_overrides:
    NukeRender:
      limits: [nuke]
    Rawline:
      limits: [rawline]
