deadline:
  host_name: deadline-manager
  port: 8082
  default_group: 8cores
  default_pool: bundle
  default_limits: 
  default_limit_groups:

  task_overrides:
    NukeRender:
      limit_groups: [nuke]

  extra_job_attributes:
    ExtraInfo0: "$SHOW"
    ExtraInfo1: "$WORKSPACE"
    ExtraInfo2: "$WORKSPACE_PATH"
    UserName: "$USER"

wolfkrow:
  host: localhost
  user: wolfkrow
  password: Gpb3s4bm
